### ISSUE TITLE
Unable to send mails through abandoned carts

### ISSUE THREAD

**Issue by dashy1981** [angela-d/abandoned-carts-opencart#14]
Hi,

I am using the plugin on 2.3.0.2.

I am unable to send out the automated mails.

 When I select a abandoned cart and click on "send message", it gives me a popup:
"From mydomain.com
Are you sure?

ok cancel"

When I click ok, it says mail sent. But none received by customers. I checked with a test account, no mail received.

Earlier questions asked with answers:
A few questions:
- On the "Are you sure?" prompt, did you hit OK?  ====> Yes
- Do your customers / test accounts receive order confirmations? Did anything land in the spam / junk folder of these email accounts?   ===> Yes they do. Nothing in spam folder.

But I must Mention:
- I am using SMTP mail configuration in system->settings->Mail.
- I had an issue where the contact us form did not work after smtp setup. So  I had to do the below modification:

File: catalog/controller/information/contact.php
Function index, for me on line 21:
ORIGINAL:
$mail->setFrom($this->request->post['email']);
NEW:
$mail->setFrom($this->config->get('config_email'));
$mail->setReplyTo($this->request->post['email']);

Possibly, I need same modification in your mailing form as well.

Pls advise.

Cheers

**Comment by angela-d** [comment]
Do you have anything in your Opencart logs?

`system/storage/logs/error.log`

If this is a similar conflict as your prior modification to contact, it should show up in that log.

`$mail->setReplyTo($this->request->post['email']);` wouldn't work for Abandoned Carts, as it doesn't take any `$this->request->post` variables to send the mail; it pulls from the shop config.

**Comment by dashy1981** [comment]
Yes, there seems some issues, I've replaced domain and user names.

2017-09-10 21:32:22 - PHP Warning:  fsockopen(): Peer certificate CN=`*.webhostbox.net' did not match expected CN=`mail.mydomain.com' in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 21:32:22 - PHP Warning:  fsockopen(): Failed to enable crypto in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 21:32:22 - PHP Warning:  fsockopen(): unable to connect to ssl://mail.mydomain.com:465 (Unknown error) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 21:32:53 - PHP Warning:  fsockopen(): Peer certificate CN=`*.webhostbox.net' did not match expected CN=`mail.mydomain.com' in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 21:32:53 - PHP Warning:  fsockopen(): Failed to enable crypto in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 21:32:53 - PHP Warning:  fsockopen(): unable to connect to ssl://mail.mydomain.com:465 (Unknown error) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 22:01:48 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 22:01:48 - PHP Warning:  fsockopen(): unable to connect to ssl://smtps.mail.mydomain.com:465 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 22:02:40 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 22:02:40 - PHP Warning:  fsockopen(): unable to connect to ssl://smtps.mail.mydomain.com:465 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 22:15:11 - PHP Warning:  fsockopen(): Peer certificate CN=`*.webhostbox.net' did not match expected CN=`mail.mydomain.com' in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 22:15:11 - PHP Warning:  fsockopen(): Failed to enable crypto in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 22:15:11 - PHP Warning:  fsockopen(): unable to connect to ssl://mail.mydomain.com:465 (Unknown error) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 22:17:06 - PHP Warning:  fsockopen(): Peer certificate CN=`*.webhostbox.net' did not match expected CN=`mail.mydomain.com' in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 22:17:06 - PHP Warning:  fsockopen(): Failed to enable crypto in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 22:17:06 - PHP Warning:  fsockopen(): unable to connect to ssl://mail.mydomain.com:465 (Unknown error) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 22:40:16 - PHP Warning:  stream_socket_enable_crypto(): Peer certificate CN=`*.webhostbox.net' did not match expected CN=`mail.mydomain.com' in /home/myusername/public_html/system/library/mail.php on line 221
2017-09-10 22:45:01 - PHP Warning:  stream_socket_enable_crypto(): Peer certificate CN=`*.webhostbox.net' did not match expected CN=`mail.mydomain.com' in /home/myusername/public_html/system/library/mail.php on line 221
2017-09-10 23:43:01 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 23:43:01 - PHP Warning:  fsockopen(): unable to connect to mail.mydomain.com :587 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 23:44:49 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 23:44:49 - PHP Warning:  fsockopen(): unable to connect to mail.mydomain.com :587 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 23:45:33 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 23:45:33 - PHP Warning:  fsockopen(): unable to connect to mail.mydomain.com :587 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 23:46:13 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 23:46:13 - PHP Warning:  fsockopen(): unable to connect to mail.mydomain.com :467 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 23:49:12 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 23:49:12 - PHP Warning:  fsockopen(): unable to connect to mail.mydomain.com :587 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 23:50:56 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-10 23:50:56 - PHP Warning:  fsockopen(): unable to connect to mail.mydomain.com :587 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-11 0:00:15 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-11 0:00:15 - PHP Warning:  fsockopen(): unable to connect to mail.mydomain.com :587 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-11 0:01:02 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-11 0:01:02 - PHP Warning:  fsockopen(): unable to connect to mail.mydomain.com :587 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-11 0:01:58 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-11 0:01:58 - PHP Warning:  fsockopen(): unable to connect to mail.mydomain.com :587 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-11 0:02:19 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-11 0:02:19 - PHP Warning:  fsockopen(): unable to connect to mail.mydomain.com :587 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-11 0:03:03 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-11 0:03:03 - PHP Warning:  fsockopen(): unable to connect to mail.mydomain.com :587 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-11 0:06:05 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-11 0:06:05 - PHP Warning:  fsockopen(): unable to connect to mail.mydomain.com :587 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-11 0:06:39 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-11 0:06:39 - PHP Warning:  fsockopen(): unable to connect to mail.mydomain.com :587 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-11 0:10:37 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-11 0:10:37 - PHP Warning:  fsockopen(): unable to connect to mail.mydomain.com :587 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/myusername/public_html/system/library/mail.php on line 167
2017-09-21 11:59:29 - PHP Notice:  Undefined index: approval in /home/myusername/public_html/catalog/model/account/customer.php on line 14
2017-09-21 11:59:29 - PHP Notice:  Undefined index: approval in /home/myusername/public_html/catalog/model/account/customer.php on line 30
2017-09-29 12:57:29 - PHP Notice:  Undefined index: approval in /home/myusername/public_html/catalog/model/account/customer.php on line 14
2017-09-29 12:57:29 - PHP Notice:  Undefined index: approval in /home/myusername/public_html/catalog/model/account/customer.php on line 30
2017-10-02 9:53:53 - PHP Notice:  Undefined index: customer_group_id in /home/myusername/public_html/admin/controller/customer/customer.php on line 1048
2017-10-02 9:53:53 - PHP Notice:  Undefined index: customer_group_id in /home/myusername/public_html/admin/model/customer/customer.php on line 28
2017-10-07 7:15:36 - PHP Notice:  Undefined index: approval in /home/myusername/public_html/catalog/model/account/customer.php on line 14
2017-10-07 7:15:36 - PHP Notice:  Undefined index: approval in /home/myusername/public_html/catalog/model/account/customer.php on line 30
2017-10-30 7:42:51 - PHP Notice:  Undefined index: approval in /home/myusername/public_html/catalog/model/account/customer.php on line 14
2017-10-30 7:42:51 - PHP Notice:  Undefined index: approval in /home/myusername/public_html/catalog/model/account/customer.php on line 30
2017-10-31 5:30:10 - PHP Notice:  Undefined variable: error_warning in /home/myusername/public_html/admin/view/template/extension/payment/pumcp.tpl on line 23
2017-10-31 5:36:09 - PHP Notice:  Undefined variable: error_warning in /home/myusername/public_html/admin/view/template/extension/payment/pumcp.tpl on line 23
2018-03-19 15:45:19 - PHP Notice:  Undefined variable: error_warning in /home/myusername/public_html/admin/view/template/extension/payment/pumcp.tpl on line 23

**Comment by dashy1981** [comment]
on a second look, those issues seems to be from last year, when I had initial issues. But at present with the changes made and smtp configured correctly, I dont see any issues in contact form or customer update mails.

The issue then was that I was unable to receive mails from contact page if the domain name was anything else but my own domain. That issue was resolved by following changes suggested at the end of this post:
[https://stackoverflow.com/questions/14306766/opencart-not-sending-emails-notifications-or-contact-page/41576022#41576022](url)

Could you suggest me how can I change the mailing form of your extension to do similiar changes.

**Comment by angela-d** [comment]
The mail errors are most definitely where to start looking; they are unrelated to Abandoned Carts but definitely are a signal  there's a misconfiguration with how your mail is set up.

```html
PHP Warning: fsockopen(): Peer certificate CN=*.webhostbox.net' did not match expected CN=mail.mydomain.com
```
There appears to be a mismatch between the mail server's SSL certificate and what you're trying to send mail with.  The mail is likely dropping off here.

**Make a note of what your settings currently are, so you can revert them if your tests are unsuccessful.**

Try one test at a time, if it does not work, revert it to what it was and move onto the next.

I also recommend to clear your Opencart error logs so you can see only new stuff during these tests.

You can clear it from the UI by going to: System -> Tools -> Error Logs -> red eraser button at the top-right

1. In your Opencart settings, is the server currently `mail.mydomain.com`?
If it is not, try to change it to `mail.mydomain.com` and test.

```html
PHP Warning: fsockopen(): unable to connect to ssl://mail.mydomain.com:465
```
2. Do you have the `ssl://` prefix?  If so, remove it and try again.  In many cases, simply specifying the port is all that's needed.

Because of all of these SSL errors, I have to assume this is why you had to do extra modifications to get your contact form working.  You shouldn't have to do that.  So perhaps once you get these issues figured out, your extra fix to the contact form might also have to be reverted to stock Opencart.

**Comment by angela-d** [comment]
Oh jeez, I didn't even notice the dates.

OK, so the only 2018 entry is from a payment add on.

Do you have a version of your site downloaded to your computer that you use for local development & testing?  I don't really recommend doing testing on a live site.

Change the "From" address in your installation to a different email address of yours.  When you send a contact request, does the email land in the new mailbox?

Also try to change it from SMTP  to PHP, which will route the mail through the server rather than a third party email; which is what I suspect is happening right now (Gmail, most likely?).  Do you get notifications from Abandoned Carts, then?

**Comment by dashy1981** [comment]
Below are the results:
1. Changing to a new email in system settings ->store->Email
results:
Contact form as well as order updates work fine.
Abandoned carts mail functionality : does not work.

2. Changed Mail protocol from SMTP->Mail in settings->Mail
I just changed above setting. All else parameters kept as it is. i.e.
Mail Parameters : empty
SMTP Hostname : mail.mydomain.com
SMTP Username : sales@mydomain.com
SMTP Password : mypwd
SMTP Port : 587
SMTP Timeout : 5
results:
Contact form as well as order updates work fine.
Abandoned carts mail functionality : does not work.

Opencart error logs cleared, no new errors get generated after all above tests. I guess ssl errors were there when my configuration was incorrect, and went away when its was done correctly.

**Comment by angela-d** [comment]
Let's dump the mail object and see what's coming through.

In `admin/model/extension/module/abandoned_carts.php` add:
```php
$this->log->write($mail);
```

Below this:
```php
$mail->send();
```

In the Opencart error.log, you'll get something like this:

```php
2018-04-22 22:23:25 - Mail Object
(
    [to:protected] => jsmith@example.com
    [from:protected] => test@example.com
    [sender:protected] => Your Store
    [reply_to:protected] => 
    [subject:protected] => Incomplete Order at Your Store
    [text:protected] => [body of the message the user receives; snipped]

    [html:protected] => 
    [attachments:protected] => Array
        (
        )

    [protocol] => mail
    [smtp_hostname] => 
    [smtp_username] => 
    [smtp_password] => 
    [smtp_port] => 25
    [smtp_timeout] => 5
    [verp] => 
    [parameter] => 
)
```

^ Mine are all blank because I used PHP Mail, not SMTP.

Any errors being passed?

If not, do the same thing on contact.php and compare the two; see what is different about the dumps.

If both contact.php and abandoned_carts.php give the same object dump, then the problem lies with the SMTP server; perhaps there's something in the body of the message they're deeming as spam -- it could be anything from default verbiage down to a product name.

The best way to test, is to use an entirely different third party SMTP; I find [gmx.com](https://www.gmx.com/) to be reliable.

Some SMTP servers also have a log in your account settings (usually paid accounts); if you have one, go and see if they've trashed any recent messages.

**Comment by dashy1981** [comment]
I get below error logs:
`2018-04-23 5:06:27 - Mail Object
(
    [to:protected] => joe_6789@gmail.com
    [from:protected] => sales@mydomain.com
    [sender:protected] => xyz Systems & Technologies
    [reply_to:protected] => 
    [subject:protected] => Incomplete Order at xyz Systems & Technologies
    [text:protected] => Hi, Joe

We noticed you stopped by our shop recently and didn't complete your purchase; we just wanted to make sure this wasn't in error -- if you meant to complete checkout, you didn't complete the payment process and thus your order wasn't placed.

For your convenience, here's a list of what was in your cart:
2x Coffee beans imported pack

If your bailed cart was intentional, we'd love to hear any feedback, suggestions or complaints you can offer so we can improve our store and customer experience!

You received this message because you (or someone using your email address) recently stopped by our shop - you have not been added to any newsletter and will not receive further communication from us as a result of your order attempt (unless you explicitly signed up to our newsletter and/or product notifications). We do not forcefully sign people up to our communications.

We thank you for your interest in our merch; have an excellent day!

Regards,

xyz Systems & Technologies
https://mydomain.com/

    [html:protected] => 
    [attachments:protected] => Array
        (
        )

    [protocol] => smtp
    [smtp_hostname] => mail.mydomain.com
    [smtp_username] => sales@mydomain.com
    [smtp_password] => mypwd
    [smtp_port] => 587
    [smtp_timeout] => 5
    [verp] => 
    [parameter] => 
)

`

**Comment by dashy1981** [comment]
I got below in errors log:

2018-04-23 5:06:27 - Mail Object
(
    [to:protected] => joe_6789@gmail.com
    [from:protected] => sales@mydomain.com
    [sender:protected] => xyz Systems & Technologies
    [reply_to:protected] => 
    [subject:protected] => Incomplete Order at xyz Systems & Technologies
    [text:protected] => Hi, Joe

We noticed you stopped by our shop recently and didn't complete your purchase; we just wanted to make sure this wasn't in error -- if you meant to complete checkout, you didn't complete the payment process and thus your order wasn't placed.

For your convenience, here's a list of what was in your cart:
2x Coffee beans imported pack

If your bailed cart was intentional, we'd love to hear any feedback, suggestions or complaints you can offer so we can improve our store and customer experience!

You received this message because you (or someone using your email address) recently stopped by our shop - you have not been added to any newsletter and will not receive further communication from us as a result of your order attempt (unless you explicitly signed up to our newsletter and/or product notifications). We do not forcefully sign people up to our communications.

We thank you for your interest in our merch; have an excellent day!

Regards,

xyz Systems & Technologies
https://mydomain.com/

    [html:protected] => 
    [attachments:protected] => Array
        (
        )

    [protocol] => smtp
    [smtp_hostname] => mail.mydomain.com
    [smtp_username] => sales@mydomain.com
    [smtp_password] => mypwd
    [smtp_port] => 587
    [smtp_timeout] => 5
    [verp] => 
    [parameter] => 
)

**Comment by angela-d** [comment]
Does contact.php give out the exact same thing for a dump?  (The only things that should differ are the `subject:protected` and `text:protected` bit.)

Everything looks good on the dump, but the @gmail.com address stands out.  Over the years, I have seen Google blackholeing perfectly legitimate emails for reasons as stupid as "too many emails at once" -- possibly something that Abandoned Carts could trigger; if you're emailing 20 people (20 bailed carts) and they're all Gmail users, there's a VERY high likelihood you'll find a temporary ban on the outgoing mail, unless you have an extremely busy store that routinely sends a high volume of mail.

In order to know if this is the case, you'd need to contact your host, give them your test email addresses and say "Messages to this address are going undelivered; is there any way you can tell me if they're being throttled or dropped at the server level?" -- they can run a search on the mail logs to see if that is indeed what occurred.

If Google is indeed dropping/bouncing messages due to the sending rate, your host would have those answers.

**Comment by dashy1981** [comment]
But the same applies for the contact form as well. In that case too I'm using the same test gmail address. It works everytime. I'll check with hosting as well.

Here is the log with contact form:

2018-04-23 5:22:38 - Mail Object
(
    [to:protected] => sales@mydomain.com
    [from:protected] => sales@mydomain.com
    [sender:protected] => Joe
    [reply_to:protected] => joe_6789@gmail.com
    [subject:protected] => Enquiry rohit
    [text:protected] => hi this is to check error logs
    [html:protected] => 
    [attachments:protected] => Array
        (
        )

    [protocol] => smtp
    [smtp_hostname] => mail.mydomain.com
    [smtp_username] => sales@mydomain.com
    [smtp_password] => mypwd
    [smtp_port] => 587
    [smtp_timeout] => 5
    [verp] => 
    [parameter] => 
)

Do you see any difference ?

**Comment by angela-d** [comment]
They are not the same, reply-to is populated for your contact.php, but not with abandoned carts.  I believe earlier, you mentioned something about modifying it.

So, as another test, please modify `admin/model/extension/module/abandoned_carts.php` and below:
```php
$mail->setFrom($this->config->get('config_email'));
```

Add:
```php
$mail->setReplyTo($this->config->get('config_email'));
```

and test Abandoned Carts, again.

**Comment by dashy1981** [comment]
You were bang on target !!!! my server was throttling these mails as spoof and was blocking them.
below is the error I got from server support(names and ip changed):
`/var/log/exim_mainlog-20180422.gz:2018-04-20 23:44:00 1f9fhA-003ay0-9D <= sales@mydomain.com H=(mydomain.com) [server IP]:53140 P=esmtpa A=dovecot_login:sales@mydomain.com S=1940 T="Incomplete Order at xyz Systems &amp; Technologies" for mydomain@gmail.com
/var/log/exim_mainlog-20180422.gz:2018-04-20 23:44:00 1f9fhA-003ay0-9D => blackhole (DATA ACL discarded recipients): Message denied for spoofing attempt via SMTP Auth (From address: xyz Systems &amp; Technologies <sales@mydomain.com> IP: myserverip AuthenticatedID: sales@mydomain.com Account owner: xyzabc)
/var/log/exim_mainlog-20180422.gz:2018-04-20 23:44:00 1f9fhA-003ay0-9D Completed
`
So they suggested me : 

To resolve the issue, you need to correct the from address in your opencart script to use only "sales@mydomain.com" and remove the extra contents for "xyz Systems &amp; Technologies". Please check it from your end and let us know for any further assistance.
--

This comes from below portion of the abandoned carts mailer script:
$mail->setSender($order_info['store_name']);

I did not want to send without sender being set, as it'll show an unprofessional looking mail in the reciepient mailbox. So I changed the store name "xyz systems and Technologies" i.e. replaced "&" to "and" in system settings.

With this, everything works correctly, Now I can send mails through your module.

Just to understand more, is it possible to keep ampersand and still be able to send the mails ?
Because order update form worked even without this change all the time. Maybe I can see how they set sender parameter in the opencart order update form(when notify customer is selected). That should give a hint. I do not know the location of the order update mailer, possibly you'll know that.

But at last, thank you so much for such excellent support and for such a great free extension.

**Comment by angela-d** [comment]
How interesting!

Can you let me know how you're currently sending the "from" field on your contact form?  Is it with the same store name?

> I did not want to send without sender being set, as it'll show an unprofessional looking mail in the reciepient mailbox. So I changed the store name "xyz systems and Technologies" i.e. replaced "&" to "and" in system settings.

Abandoned Carts pulls  the store name from the name of the store that's set when the user visits your shop - if this is showing up blank, something is misconfigured in your store.

Can you open a database management tool, like phpmyadmin and navigate to the **orders** table?
Is the **store_name** field blank for any recent transaction?


If I had to guess:
```html
From address: xyz Systems &amp; Technologies <sales@mydomain.com>
```
Your provider is doing a match on the *from* field to ensure it's an account they host; so it might be just the fact you have anything other than ` <sales@mydomain.com>` - if you put something like:

 `a <sales@mydomain.com>` it might still trigger a spoof warning.

Test it out.  If this is the case, it's a feature of your host and not necessarily something you can defeat, but if you mention to them what you're trying to achieve, they may be able to give you insight on how to work with what they're doing.

**Comment by dashy1981** [comment]
Sorry for delay.

The contact form does not set the sender to store name, but sets the sender to the first name of the customer.
[sender:protected] => Joe

While in your form its set to:
$mail->setSender($order_info['store_name']);

But from field is same in both contact form as well as abandoned carts form:
[from:protected] => sales@mydomain.com

So my conclusion is that setSender does not like meta characters in the field.
Thus it does not like '&' in the storename while if I replace '&' with 'and' then it accepts it.
xyz Systems & Technologies    ====> not accepted
xyz Systems and Technologies    ====> works


I'm not an expert on php but the order update form(do'nt know its location) is doing something which allows to use '&' in the the setSender form. Possibly you can check it and update your form.

But as of now with the above change it works for me.

Cheers

**Comment by angela-d** [comment]
Have you asked your host about this?  The spoofing message isn't from Opencart but rather from the server.  I would imagine a lot of lawyers also use the ampersand in the 'from' field.

I'm a little curious if this is intentional on part of your host, or the existence of the special character in that field broke their validation so it defaulted to a spoof error code. 

The message you posted is what happened after Abandoned Carts handed off your messages to your server's mail server, Exim; so the messages made it out of Abandoned Carts.

What happens if you use other special characters, like `;` or `%` ?

> The contact form does not set the sender to store name, but sets the sender to the first name of the customer.

This is what the `$mail->setSender($order_info['store_name']);` is supposed to do. 

Do you still have your modifications in contact.php?  If so, could you attach the bits that generate the message?  The entirety of the mail object that you dumped is the part I'm most interested to see, so I can compare to abandoned carts' mail object.

**Comment by dashy1981** [comment]
I think I am not able to communicate correctly. The contact form does not set the sender to opencart website name. Only your form does. 

MAil object logs were already sent. Mentioning them again:

2018-04-23 5:22:38 - Mail Object
(
[to:protected] => sales@mydomain.com
[from:protected] => sales@mydomain.com
[sender:protected] => Joe
[reply_to:protected] => joe_6789@gmail.com
[subject:protected] => Enquiry rohit
[text:protected] => hi this is to check error logs
[html:protected] =>
[attachments:protected] => Array
(
)

[protocol] => smtp
[smtp_hostname] => mail.mydomain.com
[smtp_username] => sales@mydomain.com
[smtp_password] => mypwd
[smtp_port] => 587
[smtp_timeout] => 5
[verp] => 
[parameter] => 
)

So you see in the sende field, contact form puts the name of the customer.

However, there's another form which sends out the order updates, like setting the order status from processing to shipped or to complete. That form was working correctly even though I had '&' in the sender field. So if at all you need to compare mailing forms you should compare with that form. Unfortunately I do'nt know exact location of that form so can not provide. But it is same which comes in default opencart 2.3.0.2.


I have one suggestion to make, not sure where should I do that, so will blurt it out here :-)
- Instead of giving the text name of products customer added to abandoned cart, if you can provide the text name as a hyperlink to the product that will be a valuable addition.

**Comment by angela-d** [comment]
Can you set this to the `setSender` in abandoned carts and see if you can send with the &?
```php
$mail->setSender(html_entity_decode($store_name, ENT_QUOTES, 'UTF-8'));
```

> Instead of giving the text name of products customer added to abandoned cart, if you can provide the text name as a hyperlink to the product that will be a valuable addition.

The problem with doing so is say someone has a large cart with a lot of items, that will increase the potential spam score of the outgoing mail; many mail servers will see a heap of links and interpret it poorly.

It is assumed most folks that use this plugin aren't using third-party smtp that has an established sender score to send from, so the messages are analyzed by recipient servers more harshly.

**Comment by dashy1981** [comment]
I get below error when setting the sender as you mentioned:

`Fatal error: Uncaught exception 'Exception' with message 'Error: E-Mail sender required!' in /home/xyz/public_html/system/library/mail.php:68 Stack trace: #0 /home/xyz/public_html/admin/model/extension/module/abandoned_carts.php(56): Mail->send() #1 [internal function]: ModelExtensionModuleAbandonedCarts->recoverEmail('5678') #2 /home/xyz/public_html/system/storage/modification/system/engine/loader.php(178): call_user_func_array(Array, Array) #3 [internal function]: Loader->{closure}(Array, Array) #4 /home/xyz/public_html/system/engine/proxy.php(25): call_user_func_array(Object(Closure), Array) #5 /home/xyz/public_html/admin/controller/report/abandoned_carts.php(24): Proxy->__call('recoverEmail', Array) #6 /home/xyz/public_html/admin/controller/report/abandoned_carts.php(24): Proxy->recoverEmail('5678') #7 [internal function]: ControllerReportAbandonedCarts->recover() #8 /home/xyz/public_html/system/storage/modification/system/engine/action.php(51): call_user_func_array(Array, Array) #9 in /home/xyz/public_html/system/library/mail.php on line 68

Below is the line 68:


	public function getOrders($data = array()) {
		$implode = array();

		if ($this->config->get('abandoned_carts_criteria')){
			foreach ($this->config->get('abandoned_carts_criteria') as $criteria) {
				$implode[] = "'" . (int)$criteria . "'";      ===============> Line 68
			}

		$criteria_statuses = implode(" OR ", $implode);
		}`

The reason for not sending links understood. Thanks.

**Comment by angela-d** [comment]
The error is originating from `/home/xyz/public_html/system/library/mail.php` on line 168; it's not actually coming from abandoned carts.  Open Cart can't see what it is expecting, so it throws this error.

I made a typo in my prior suggestion (sorry!) - the literal interpretation should be this:
```php
$mail->setSender(html_entity_decode($order_info['store_name'], ENT_QUOTES, 'UTF-8'));
```

to pull from the shop the user visited while browsing your store.  You could also change it to pull the store name from your configuration controlled by settings, but this would break any multi-store setup; so the ideal method of handling this would be to pull it from the user's order data.

**Comment by dashy1981** [comment]
Great... Now mails are being sent(even if "&" is present in the store name).

But the issue popped up in subject :

Incomplete Order at xyz Systems &amp; Technologies

I took a clue from your last change and changed the subject line from:
original: $mail->setSubject($language->get('subject_prefix').' '.$order_info['store_name']);
changed: $mail->setSubject($language->get('subject_prefix').' '.html_entity_decode($order_info['store_name'], ENT_QUOTES, 'UTF-8'));

Now everything works great !!!!!

**Comment by dashy1981** [comment]
same change needed at one more place:
//$text .= $order_info['store_name'] . "\n";
$text .= html_entity_decode($order_info['store_name'], ENT_QUOTES, 'UTF-8') . "\n";

This one is used to print storename at the footer of the message.

One last issue I've got:
The store url in the mail footer is coming as https://xyz.com/
While I'd like it to be https://xyz.com     with no trailing /. Can you suggest any change ?

**Comment by angela-d** [comment]
Awesome!!! I will push this through as a bugfix today; thanks for taking the time to test it!

The trailing / is coming from admin/config.php -- if you remove it, it may break other stuff on the site.
So, for a quick fix, change:
```php
		$text .= $order_info['store_url'] . "\n";
```
to:
```php
		str_replace('/','',$text .= $order_info['store_url']) . "\n";
```

You would need to do this tweak anytime you update the plugin.

**Comment by dashy1981** [comment]
Cool Thx, for support !!!!
